# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

normalize_matrix <- function(M, cmM, mM) {
    .Call(`_MVS_normalize_matrix`, M, cmM, mM)
}

hadamard_product <- function(X, Y) {
    .Call(`_MVS_hadamard_product`, X, Y)
}

vector_product <- function(X, Y) {
    .Call(`_MVS_vector_product`, X, Y)
}

matrix_prod_sum <- function(X, Y) {
    .Call(`_MVS_matrix_prod_sum`, X, Y)
}

vector_prod_sum <- function(X, Y) {
    .Call(`_MVS_vector_prod_sum`, X, Y)
}

specific_vector_prod_sum <- function(X, Y, gamma_1, gamma_X, gamma_Y, gamma_XY) {
    .Call(`_MVS_specific_vector_prod_sum`, X, Y, gamma_1, gamma_X, gamma_Y, gamma_XY)
}

matrix_sum <- function(X) {
    .Call(`_MVS_matrix_sum`, X)
}

vector_prod_sum_sample <- function(X, Y, s) {
    .Call(`_MVS_vector_prod_sum_sample`, X, Y, s)
}

